services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Burlington123!
    ports:
      - "1433:1433"

  api:
    build:
      context: ./DbProjectExample
      dockerfile: Dockerfile
    ports:
      - "5062:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=GroceryDb;User Id=SA;Password=Burlington123!;TrustServerCertificate=True;
    depends_on:
      - db
